@uri=http://localhost:3001/

###
GET {{uri}}users

###
POST {{uri}}register
Content-Type: application/json

{
  "username": "admin3",
  "password": "admim"
}

###
POST {{uri}}login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admim"
}

###
GET {{uri}}userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlM2VkNWJmODgxNjA3MzcwY2EzNTYyNSIsImlhdCI6MTU4MTE3NjU5Mn0.JJ8pGYRcD-dkxE-to_-sAJc-XySbqyBeG3ZrOEWo5iI
